version: '3'
services:
  convert-fbx-binary:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_binary.py resources/cube.obj resources/cube_binary.fbx

  convert-fbx-ascii:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_ascii.py resources/cube_binary.fbx resources/cube_ascii.fbx

  convert-fbx-binary-7200:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_binary_7200.py resources/cube.obj resources/cube_binary.fbx

  convert-fbx-ascii-7200:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_ascii_7200.py resources/cube_binary.fbx resources/cube_ascii.fbx

  list-format:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./show:/src/show
    working_dir: /src
    command: python show/list_format.py

  show-attribute:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./show:/src/show
    working_dir: /src
    command: python show/show_attribute.py resources/cube_binary.fbx

  generate-camera-anim:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./generate_fbx:/src/generate_fbx
    working_dir: /src
    command: python generate_fbx/camera_anim.py resources/camera_anim_ascii.fbx

  generate-cube-anim:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./generate_fbx:/src/generate_fbx
    working_dir: /src
    command: python generate_fbx/generate_anim.py resources/cube_ascii.fbx resources/moving_cube_ascii.fbx

  moving-circle-cube:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./generate_fbx:/src/generate_fbx
    working_dir: /src
    command: python generate_fbx/circle_anim.py resources/cube_ascii.fbx resources/moving_circle_cube_ascii.fbx
